name: Build and Push to Docker

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_main:
    runs-on: ubuntu-latest
        
    steps:
    - name: Calculate Version
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        echo "BUILD_NUMBER=$(($BUILD_NUMBER + 1000))" >> $GITHUB_ENV
  
    - name: Set up qemu
      uses: docker/setup-qemu-action@v3.6.0
    
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: BUILD AND PUSH
      id: docker_build
      uses: docker/build-push-action@v6.18.0
      with:
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: pangostack-local

    - name: Publish - Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish - Rename Tags
      if: github.event_name != 'pull_request'
      run: |
        docker tag pangostack-local squidex/pangostack-dev
        docker tag pangostack-local squidex/pangostack-dev:${{ env.BUILD_NUMBER }}
  
    - name: Publish - Push Tags
      if: github.event_name != 'pull_request'
      run: |
        docker push squidex/pangostack-dev
        docker push squidex/pangostack-dev:${{ env.BUILD_NUMBER }}

  build_worker:
    runs-on: ubuntu-latest
        
    steps:
    - name: Calculate Version
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        echo "BUILD_NUMBER=$(($BUILD_NUMBER + 1000))" >> $GITHUB_ENV
  
    - name: Set up qemu
      uses: docker/setup-qemu-action@v3.6.0
    
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: BUILD AND PUSH
      id: docker_build
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./services/worker
        file: ./services/worker/Dockerfile
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: pangostack-worker-local

    - name: Publish - Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish - Rename Tags
      if: github.event_name != 'pull_request'
      run: |
        docker tag pangostack-worker-local squidex/pangostack-worker-dev
        docker tag pangostack-worker-local squidex/pangostack-worker-dev:${{ env.BUILD_NUMBER }}
  
    - name: Publish - Push Tags
      if: github.event_name != 'pull_request'
      run: |
        docker push squidex/pangostack-worker-dev
        docker push squidex/pangostack-worker-dev:${{ env.BUILD_NUMBER }}
